agent_options:
labels:
- description: macOS hosts on Apple Silicon architecture
  label_membership_type: dynamic
  name: Apple Silicon macOS hosts
  platform: darwin
  query: SELECT 1 FROM os_version WHERE arch LIKE 'ARM%';
- description: Windows hosts on ARM architecture
  label_membership_type: dynamic
  name: ARM-based Windows hosts
  platform: windows
  query: SELECT 1 FROM os_version WHERE arch LIKE 'ARM%';
- description: Linux hosts running on Debian-based operating systems
  label_membership_type: dynamic
  name: Debian-based Linux hosts
  query: SELECT 1 FROM os_version WHERE platform_like = 'debian';
- description: Windows hosts on x86 architecture
  label_membership_type: dynamic
  name: x86-based Windows hosts
  platform: windows
  query: SELECT * FROM os_version WHERE arch NOT LIKE 'ARM%';
controls:
  enable_disk_encryption: false
  enable_recovery_lock_password: false
  ios_updates:
    deadline:
    minimum_version:
    update_new_hosts:
  ipados_updates:
    deadline:
    minimum_version:
    update_new_hosts:
  macos_updates:
    deadline:
    minimum_version:
    update_new_hosts:
  scripts:
  windows_require_bitlocker_pin: false
  windows_updates:
    deadline_days:
    grace_period_days:
org_settings:
  activity_expiry_settings:
    activity_expiry_enabled: false
    activity_expiry_window: 0
    preserve_host_activities_on_reenrollment: false
  certificate_authorities:
    custom_est_proxy:
    custom_scep_proxy:
    digicert:
    hydrant:
    ndes_scep_proxy:
    smallstep:
  features:
    enable_host_users: true
    enable_software_inventory: true
    historical_data:
      uptime: true
      vulnerabilities: true
  fleet_desktop:
    alternative_browser_host:
    transparency_url: https://fleetdm.com/transparency
  host_expiry_settings:
    host_expiry_enabled: false
    host_expiry_window: 0
  integrations:
    conditional_access_enabled: false
    google_calendar:
    jira:
    zendesk:
  mdm:
    apple_business:
    apple_server_url:
    end_user_authentication:
      entity_id:
      idp_name:
      issuer_uri:
      metadata:
      metadata_url:
    end_user_license_agreement:
    volume_purchasing_program:
  org_info:
    contact_url: https://fleetdm.com/company/contact
    org_logo_url_dark_mode:
    org_logo_url_light_mode:
    org_name: Fleet for osquery
  server_settings:
    ai_features_disabled: false
    deferred_save_host: false
    discard_reports_data: false
    enable_analytics: true
    live_reporting_disabled: false
    report_cap: 0
    scripts_disabled: false
    server_url: https://localhost:8412
  sso_settings:
  webhook_settings:
    activities_webhook:
      destination_url:
      enable_activities_webhook: false
    failing_policies_webhook:
      destination_url:
      enable_failing_policies_webhook: false
      host_batch_size: 0
    host_status_webhook:
      days_count: 0
      destination_url:
      enable_host_status_webhook: false
      host_percentage: 0
    interval: 24h0m0s
    vulnerabilities_webhook:
      destination_url:
      enable_vulnerabilities_webhook: false
      host_batch_size: 0
  yara_rules:
policies:
reports: